word = str(input('Digite algo: '))
print(f'O tipo primitivo desse valor é {type(word)}')
print(f'Só tem espaços? {word.isspace()}')
print(f'É um número? {word.isnumeric()}')
print(f'É alfabético? {word.isalpha()}')
print(f'Está em maiúsculas? {word.isupper()}')
print(f'Está em minusculas? {word.islower()}')
print(f'Está capitalizada? {word.istitle()}')